export * from './Archive';
export * from './ForgotPassword';
export * from './Home';
export * from './Login';
export * from './NotFound';
export * from './Product';
export * from './Profile';
export * from './Shop';
export * from './SignUp';
